### PR TITLE
Fix invalid exception from urlencoded cookie value

### LINKED ISSUE #15: cookie values decode error
Hi!
I have found one problem with encoding.

In PHP it's normal behavior that values are urlencoded, but in other languages there are another standards for encoding such value, for example - in python.

So, cookie created in python could be invalid after urldecode here:
https://github.com/zendframework/zend-http/blob/master/src/Header/SetCookie.php#L119

But if we want to fix that issue, we suppose to get rid of that urlencode also:
https://github.com/zendframework/zend-http/blob/master/src/Header/SetCookie.php#L236

That is wrong, cause when we try to set cookie with specific symbols - we get wrong cookie.

I really don't know how to fix problem, have anyone ideas?

I thought that best approach is to add client type (php, python) and add specific decode/encode functions for each type, also add default type which only encode values.

At now I have a site that causes Zend Http Client failed on send method:

``` php
        $client = new Client('http://www.gd.ru/articles/3514-uvelichenie-prodaj');
        $client->send();
```

### PR DESCRIPTION
**Pull request by zerocrates**
This is my alternative solution to #15, as a replacement for the existing PR #16.

This PR fixes the problem by simply re-urlencoding the cookie value before validating it. This is allowable because the actual cookie as output *also* urlencodes the value (see [SetCookie::getFieldValue](https://github.com/zerocrates/zend-http/blob/master/src/Header/SetCookie.php#L236).

As a concrete example, this PR removes the test `testPreventsCRLFAttackViaConstructor`. The change makes that test fail, but the test was already failing for an input that wouldn't have actually enabled a CRLF attack. The "evil" example is:

```php
$header = new SetCookie("leo_auth_token", "example\r\n\r\nevilContent");
```

However, under both the existing code and after the commit in this PR, that SetCookie header creates no CRLF injection problems, because SetCookie already automatically urlencodes values on output. So, the output of `$header->toString()` on the above "evil" cookie is already safe:

```
Set-Cookie: leo_auth_token=example%0D%0A%0D%0AevilContent
```

I think this change is the best way to fix the regression without compromising the security the validation was introduced to provide and without surprising users by changing the header's behavior.

Fix #15
Supersede & close #16

### CODE REVIEW

File: src/Header/SetCookie.php [hunk 1]
```diff
@@ -302,7 +302,7 @@ public function getName()
      */
     public function setValue($value)
     {
-        HeaderValue::assertValid($value);
+        HeaderValue::assertValid(urlencode($value));
```
Comment (Maks3w) [inline src/Header/SetCookie.php]: When this won't be valid? if there no case exists then remove whole line.

File: test/Header/SetCookieTest.php [hunk 2]
```diff
@@ -425,16 +425,6 @@ public function testPreventsCRLFAttackViaFromString()
         $header = SetCookie::fromString("Set-Cookie: leo_auth_token=example;\r\n\r\nevilContent");
     }
 
-    /**
```
Comment (Maks3w) [inline test/Header/SetCookieTest.php]: Don't remove the test, Instead assert the value is valid. If not regressions are welcome :)

**Comment by zerocrates** [comment]
I see, yeah that's a much better solution. I've replaced my initial commit with one that follows your suggestions.

File: test/Header/SetCookieTest.php [hunk 3]
```diff
@@ -431,8 +432,8 @@ public function testPreventsCRLFAttackViaFromString()
      */
     public function testPreventsCRLFAttackViaConstructor()
     {
-        $this->setExpectedException('Zend\Http\Header\Exception\InvalidArgumentException');
         $header = new SetCookie("leo_auth_token", "example\r\n\r\nevilContent");
+        $this->assertTrue(HeaderValue::isValid($header->getFieldValue()));
```
Comment (Maks3w) [inline test/Header/SetCookieTest.php]: I preffer if you assertEquals against the __toString() output. Will be more clear to understand because the encoded characters will be visible while reading this code.

Comment (Maks3w) [inline test/Header/SetCookieTest.php]: Could you add an additional test method for unit check of `setValue`?

**Comment by zerocrates** [comment]
Okay. (I assume the extra test method is what you were looking for, if not let me know)

**Comment by Maks3w** [comment]
@weierophinney Please add this one to 2.4.8 LTS

**Comment by weierophinney** [comment]
Tagged in release-2.5.2 and 2.4.8.
